### ISSUE TITLE
Timestamp issue on ERCOT SPP data pull?

### ISSUE THREAD

**Issue by joshdr83** [gridstatus/gridstatusio#16]
When I run the example ["Retrieving data in local time"](https://github.com/gridstatus/gridstatusio/blob/main/Examples/Getting%20Started.ipynb), I still seeing the timestamp in UTC... It also looks like it isn't lining up with the [ERCOT data](https://www.ercot.com/mp/data-products/data-product-details?id=NP6-905-CD) that I am finding on the website.

![image](https://github.com/gridstatus/gridstatusio/assets/3343052/4af740e2-651f-4ebc-bd43-c4995582cdf5)

![image](https://github.com/gridstatus/gridstatusio/assets/3343052/c7e2e45a-f0e6-425b-940f-c6bd35a552c7)

Or the data are 4 hours off?

![image](https://github.com/gridstatus/gridstatusio/assets/3343052/8827ce83-1c1b-43cf-984f-3c1e0212afa3)

**Comment by kmax12** [comment]
it looks like the time zone conversion isn't happening correctly and the date is staying in utc.

what version of the grid status client library are you using?

```python
>>> import gridstatusio
>>> import pandas
>>> gridstatusio.__version__
'0.4.0'
>>> pandas.__version__
'2.0.1'
```

**Comment by joshdr83** [comment]
Here is what I have up and running in this environment

￼

Joshua Rhodes

**Comment by joshdr83** [comment]
Here is what I have:

![image](https://github.com/gridstatus/gridstatusio/assets/3343052/5c2f8516-6d2a-43df-b62f-16a4d2fc6720)

**Comment by kmax12** [comment]
thanks! i was able to reproduce and fix the error when I downgraded to that version of pandas. 

just  released version 0.5.0 of gridstatusio. if you upgrade to that, everything should work. let me know if you see any other problems

**Comment by joshdr83** [comment]
Hi Max

I seem to be getting a similar timestamp conversion error with the “ercot_fuel_mix” data after updating to the latest packages? I see solar production that appears to be indexed via UTC time even when asking for local?

Thanks!

Joshua Rhodes

￼￼


￼

**Comment by kmax12** [comment]
Hi Joshua - im not able to reproduce. can you share the code you are using the versions of pandas and gridstatus that you are using? 

<img width="937" alt="image" src="https://github.com/gridstatus/gridstatusio/assets/371792/de027d09-47f6-4d2e-8cd8-fdb55c69166f">

**Comment by joshdr83** [comment]
Right, but it looks like that the solar doesn't start producing until late in the afternoon, well after the sun has come up and keeps on producing well into the night after the sun has gone down?

<img width="954" alt="image" src="https://github.com/gridstatus/gridstatusio/assets/3343052/47a0c47a-38aa-47f6-9809-a03f49747c29">

<img width="939" alt="image" src="https://github.com/gridstatus/gridstatusio/assets/3343052/42ac85d3-d5f2-426a-aa52-148116a422e1">
